server:
  build: .
  dockerfile: ./Dockerfile
  working_dir: /app/books
  volumes:
    - .:/app/books
  links:
   - db
  # volumes:
  #   - /Users/viveksoundrapandi/Desktop/2019/pythontest/book_app/:/app/books
  ports:
    - "5000:5000"
  environment:
    PYTHONPATH: $PYTHONPATH:/app/books/src
  command: python src/server.py

db:
  image: postgres:9.4
  restart: always